swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Starwars"
  termsOfService: "http://localhost:3003"
  contact:
    email: "d.k1994@interia.pl"
host: "localhost:3003"
basePath: "/dev"
tags:
- name: "characters"
  description: "Operations about character"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /characters:
    post:
      tags:
      - "characters"
      summary: "Create new character"
      operationId: "createCharacter"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created character object"
        required: true
        schema:
          $ref: "#/definitions/Character"
      responses:
          "200":
              description: "successful operation"
              schema:
                $ref: "#/definitions/CharacterResponse"
          "400":
            description: "Bad request"
            schema:
              $ref: "#/definitions/ErrorResponse"
          "500":
            description: "Internal Server Error"
            schema:
              $ref: "#/definitions/ErrorResponse"
    get:
      tags:
      - "characters"
      summary: "Get characters from db - limited to 10 per one request"
      description: ""
      operationId: "getCharacters"
      produces:
      - "application/json"
      parameters:
      - name: "lastSearch"
        in: "query"
        description: "For paggination. If you want go to next page paste here last selected characterId"
        required: false
        type: "string"
      responses:
        "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/CharacterResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /characters/{characterId}:
    get:
      tags:
      - "characters"
      summary: "Find one character in db by ID"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "characterId"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CharacterResponse"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"  
    put:
      tags:
      - "characters"
      summary: "Updated character"
      operationId: "updateCharacter"
      produces:
      - "application/json"
      parameters:
      - name: "characterId"
        in: "path"
        description: "Id that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated character object"
        required: true
        schema:
          $ref: "#/definitions/Character"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
      - "characters"
      summary: "Delete character"
      operationId: "deleteCharacter"
      produces:
      - "application/json"
      parameters:
      - name: "characterId"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Character:
    type: "object"
    properties:
      name:
        type: "string"
      episodes:
        type: "array"
        items:
          type: string
      friends:
        type: "array"
        items:
          type: string
  CharacterResponse:
      properties:
        name:
          type: string
        episodes:
          type: "array"
          items:
            type: string
        friends:
          type: "array"
          items:
            type: string
        characterId:
          type: string
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"